# Generated by Django 6.0.6 on 2026-06-29 20:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=150)),
                ('element', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nom_service', 'element'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('raison_sociale', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('est_locale', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme-Nord', 'Extrême-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord-Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest')], max_length=50, null=True)),
                ('branche_activite', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture & Agroalimentaire'), ('BTP', 'BTP & Construction'), ('Commerce', 'Commerce & Distribution'), ('Energie', 'Énergie & Mines'), ('Finance', 'Finance & Assurance'), ('Industrie', 'Industrie & Manufacture'), ('Numerique', 'Numérique & Télécoms'), ('Sante', 'Santé & Pharmaceutique'), ('Services', 'Services aux entreprises'), ('Transport', 'Transport & Logistique'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('doc_registre_commerce', models.FileField(upload_to='documents/')),
                ('doc_contribuable', models.FileField(upload_to='documents/')),
                ('doc_autre', models.FileField(upload_to='documents/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Entreprise',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BesoinOffreEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besoin', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins_offres', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins_offres', to='entreprises.service')),
            ],
            options={
                'unique_together': {('entreprise', 'service', 'besoin')},
            },
        ),
    ]
