# Generated by Django 6.0.6 on 2026-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='doc_autre',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
