# Generated by Django 6.0.6 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_alter_entreprise_doc_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
